version: '3.8'

services:
  api:
    build: .
    container_name: multi_tenant_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb
      - redis
    environment:
      - DATABASE_URL=postgresql://<dbusername>:<dbpassword>@postgres:5432/multi_tenant_db
      - MONGO_URI=mongodb://<username>:<password>@mongodb:27017/audit_logs_db
      - SECRET_KEY=your-secret-key

  citus_coordinator:
    image: citusdata/citus
    container_name: citus_coordinator
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raja
      POSTGRES_DB: multi_tenant_db
    ports:
      - "5432:5432"
    volumes:
      - citus_coordinator_data:/var/lib/postgresql/data
    depends_on:
      - citus_worker1
      - citus_worker2

  citus_worker1:
    image: citusdata/citus
    container_name: citus_worker1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raja
      POSTGRES_DB: multi_tenant_db
    volumes:
      - citus_worker1_data:/var/lib/postgresql/data

  citus_worker2:
    image: citusdata/citus
    container_name: citus_worker2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raja
      POSTGRES_DB: multi_tenant_db
    volumes:
      - citus_worker2_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:6.0
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo_data:/data/db



volumes:
  citus_coordinator_data:
    driver:  local
  citus_worker1_data:
    driver: local
  citus_worker2_data:
    driver: local
  mongo_data:
    driver: local
